"""Generate directly deployable HTML. Python 3.10+, no dependencies."""
from pathlib import Path
import json
from html import escape as e
ROOT=Path(__file__).resolve().parent.parent
P=json.loads((ROOT/'content/projects.json').read_text(encoding='utf-8'))
PROFILE=json.loads((ROOT/'content/profile.json').read_text(encoding='utf-8'))

def link(url,text,cls='text-link'):
 return f'<a class="{cls}" href="{e(url)}" target="_blank" rel="noopener noreferrer">{e(text)} <span aria-hidden="true">↗</span></a>'
def tags(p):
 return '<ul class="tags" aria-label="사용 기술">'+''.join(f'<li>{e(t)}</li>' for t in p['stack'])+'</ul>'
def media(p,prefix='',i=0):
 im=p['images'][i]
 return f'<img src="{prefix}assets/projects/{im["src"]}" alt="{e(im["alt"])}" width="1200" height="800" loading="lazy" decoding="async">'
def shell(title,body,prefix='',description=''):
 description=description or 'STM32 펌웨어부터 ROS 2와 다중 로봇 FMS까지. 이명욱의 실제 프로젝트와 본인 기여를 소개합니다.'
 home=prefix+'index.html' if prefix else ''
 return f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{e(title)} | 이명욱</title><meta name="description" content="{e(description)}"><meta name="theme-color" content="#14243b"><meta property="og:type" content="website"><meta property="og:title" content="{e(title)} | 이명욱"><meta property="og:description" content="{e(description)}"><link rel="icon" href="{prefix}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{prefix}style.css"><script src="{prefix}script.js" defer></script></head><body>
<a class="skip-link" href="#main">본문으로 바로가기</a><header class="site-header"><nav class="container nav" aria-label="주 메뉴"><a class="brand" href="{home}#home" aria-label="이명욱 포트폴리오 홈"><span class="brand-mark">MW<span>.</span></span><span class="brand-name">이명욱 <span>/ PORTFOLIO</span></span></a><button class="menu-toggle" type="button" aria-controls="nav-links" aria-expanded="false">메뉴 <span aria-hidden="true">☰</span></button><div class="nav-links" id="nav-links"><a href="{home}#projects">Projects</a><a href="{home}#about">About</a><a href="{home}#skills">Skills</a><a href="{home}#contact">Contact</a>{link(PROFILE['github'],'GitHub','nav-github')}</div></nav></header><main id="main">{body}</main><footer class="site-footer"><div class="container footer-inner"><p>© 2026 이명욱 <span>Robot Software / Embedded</span></p><a href="{home}#home">맨 위로 ↑</a></div></footer></body></html>'''
def card(p):
 return f'''<article class="project-card" data-category="{p['type']}"><a class="project-image" href="projects/{p['id']}.html" aria-label="{e(p['name'])} 프로젝트 상세">{media(p)}<span class="image-label">{p['number']} / {e(p['category'].split(' / ')[0])}</span><span class="image-arrow" aria-hidden="true">↗</span></a><div class="card-body"><p class="card-meta">{e(p['period'])}<span>{e(p['team'])}</span></p><h3><a href="projects/{p['id']}.html">{e(p['name'])}</a></h3><p class="card-summary">{e(p['summary'])}</p><p class="card-role"><span>MY ROLE</span>{e(p['role'])}</p>{tags(p)}<a class="card-more" href="projects/{p['id']}.html">구현과 기여 보기 <span aria-hidden="true">↗</span></a></div></article>'''
def homepage():
 p=P[0]
 email=link('mailto:'+PROFILE['email'],'Email','button button-quiet') if PROFILE['email'] else '<a class="button button-quiet" href="#contact">연락처 ↓</a>'
 return f'''
<section class="hero container" id="home"><div class="hero-copy"><p class="eyebrow">ROBOT SOFTWARE / EMBEDDED</p><h1>센서의 신호를<br>로봇의 <span>움직임으로.</span></h1><p class="hero-name">개발자 이명욱<span>Myeonguk Lee</span></p><p class="hero-description">STM32 기반 하위 제어부터 ROS 2 로봇 소프트웨어와<br class="desktop-break"> Multi-Robot FMS까지, 실제 장치를 연결하며 배웁니다.</p><div class="hero-actions"><a class="button button-primary" href="#projects">프로젝트 살펴보기 ↘</a>{link(PROFILE['github'],'GitHub','button button-secondary')}{email}</div></div>
<div class="hero-system" aria-label="임베디드부터 로봇 소프트웨어와 FMS까지의 프로젝트 경험"><div class="system-heading"><span>SYSTEM INTEGRATION</span><span aria-hidden="true">+</span></div><p class="system-title">연결하며 넓혀온 개발 경험</p><div class="system-layer"><span class="layer-index">03</span><div><strong>Multi-Robot FMS</strong><span>Zenoh · 상태 관리 · 관제 연동</span></div><span class="layer-dot" aria-hidden="true"></span></div><div class="layer-connector" aria-hidden="true">↕</div><div class="system-layer"><span class="layer-index">02</span><div><strong>Robot Software</strong><span>ROS 2 · 센서 데이터 · Nav2 적용</span></div></div><div class="layer-connector" aria-hidden="true">↕</div><div class="system-layer"><span class="layer-index">01</span><div><strong>Embedded Firmware</strong><span>STM32 · FreeRTOS · 모터 제어</span></div></div><div class="system-foot"><span class="small-dot"></span>현재 집중하는 분야 <strong>AMR / FMS</strong></div></div></section>
<div class="container focus-line"><span>관심 직무</span><p>Robot Software <span>/</span> AMR <span>/</span> Embedded Firmware <span>/</span> System Integration</p></div>
<section class="section container" id="projects"><div class="section-head"><div><p class="eyebrow">01 / SELECTED WORK</p><h2>코드가 실제 동작이 되기까지</h2></div><p>구현한 내용과 남은 한계를 <br>프로젝트별로 기록했습니다.</p></div><article class="featured"><a class="featured-visual" href="projects/fms.html" aria-label="AX Logistics MultiBot 프로젝트 상세">{media(p)}<span class="visual-caption">실제 Route Graph 데이터 · 구성도</span></a><div class="featured-content"><p class="feature-top"><span>FEATURED PROJECT</span><span class="status"><span class="small-dot"></span>진행 중</span></p><h3>{e(p['name'])}</h3><p>{e(p['summary'])}</p><p class="featured-role"><span>MY ROLE</span>{e(p['role'])}</p>{tags(p)}<div class="feature-scope"><div><strong>현재 구현</strong><p>통신 · 상태 연동 · Mock Fleet</p></div><div><strong>향후 구현·검증</strong><p>교통관리 · OMX · VLM 비교</p></div></div><div class="feature-links"><a class="text-link" href="projects/fms.html">구현과 기여 보기 ↗</a>{link(p['github'],'GitHub')}</div></div></article>
<div class="projects-toolbar"><h3>Project Archive <span>05</span></h3><div class="filters" role="group" aria-label="프로젝트 분야 필터" hidden><button type="button" data-filter="all" aria-pressed="true">전체</button><button type="button" data-filter="robot" aria-pressed="false">Robot SW</button><button type="button" data-filter="embedded" aria-pressed="false">Embedded</button></div></div><p class="sr-only" id="filter-status" role="status" aria-live="polite"></p><div class="project-grid">{''.join(card(x) for x in P[1:5])}</div>
<article class="mini-project" data-category="embedded"><a class="mini-image" href="projects/plc.html" aria-label="PLC 프로젝트 상세">{media(P[5])}</a><div><p class="eyebrow">06 / TRAINING PROJECT</p><h3>PLC Mini Project</h3><p>Mitsubishi PLC와 HMI로 창고 적재·비우기·수동 제어를 연결한 2인 교육 프로젝트.</p><p class="mini-stack">GX Works2 · Ladder Logic · Sequence Control</p></div><a class="text-link" href="projects/plc.html">자세히 보기 ↗</a></article></section>
<section class="about-section" id="about"><div class="container about-grid"><div><p class="eyebrow">02 / ABOUT</p><h2>직접 연결하고,<br>움직임으로 확인합니다.</h2><p class="about-copy">센서 값을 읽는 코드에서 시작해 모터, 로봇 소프트웨어, 관제 화면으로 관심을 넓혀왔습니다. 서로 다른 장치의 데이터가 실제 동작으로 이어지는 과정에 흥미를 느낍니다.</p><p class="about-copy">기존 패키지와 AI의 도움을 활용하되 코드를 이해하고 수정하며 배웁니다. 구현한 것과 검증하지 못한 것을 구분해 기록하려고 합니다.</p></div><div class="education"><p class="eyebrow">EDUCATION & DIRECTION</p><article><span class="education-date">2026.04 – 11 예정 · 수강 중</span><h3>대한상공회의소 서울기술교육센터</h3><p>AI융합 로봇 SW 개발자 과정 3기</p></article><article><span class="education-date">학력</span><h3>인덕대학교 정보통신공학</h3><p>임베디드 제어와 로봇 프로젝트 경험</p></article><article><span class="education-date">현재 개발 방향</span><h3>AMR와 로봇 시스템 통합</h3><p>ROS 2 로봇과 다중 로봇 관제 사이의 통신·상태 흐름</p></article></div></div></section>
<section class="section container" id="skills"><div class="section-head"><div><p class="eyebrow">03 / TOOLBOX</p><h2>프로젝트에서 사용한 기술</h2></div><p>숙련도 숫자 대신 <br>어디에 적용했는지 보여드립니다.</p></div><div class="skill-grid"><article class="skill-group"><span class="skill-no">01</span><h3>Languages</h3><p>C · C++ · Python<br>Java · Dart</p><a href="projects/gosung.html">펌웨어·ROS 2·앱 구현 ↗</a></article><article class="skill-group"><span class="skill-no">02</span><h3>Robot Software</h3><p>ROS 2 Humble / Jazzy · Nav2<br>OpenCV · Camera Calibration</p><a href="projects/gosung.html">센서 처리와 주행 패키지 연동 ↗</a></article><article class="skill-group"><span class="skill-no">03</span><h3>Embedded</h3><p>STM32F407 / H743 · FreeRTOS<br>UART · I2C · DMA · Timer / PWM</p><a href="projects/aiming.html">영상 입력과 제어 태스크 ↗</a></article><article class="skill-group"><span class="skill-no">04</span><h3>Integration</h3><p>Linux · Zenoh · FastAPI<br>Bluetooth · Firebase · Git</p><a href="projects/fms.html">로봇과 관제 시스템 연결 ↗</a></article></div><p class="skills-note">SLAM Toolbox·AMCL은 매핑·위치 추정 패키지 사용 경험이 있습니다. Planner·Controller 내부 알고리즘 개발과는 구분합니다.</p></section>
<section class="contact-section" id="contact"><div class="container contact-inner"><div><p class="eyebrow">04 / CONTACT</p><h2>다음 로봇의 움직임을<br>함께 만들어가고 싶습니다.</h2><p>프로젝트의 코드와 구현 기록은 GitHub에서 확인할 수 있습니다.</p></div><div class="contact-links">{link(PROFILE['github'],'GitHub · Ugie01','button button-light')}{link('mailto:'+PROFILE['email'],PROFILE['email'],'contact-email') if PROFILE['email'] else ''}<span>Robot Software / Embedded</span></div></div></section>'''
def detail(p):
 actions=(link(p['github'],'View GitHub','button button-primary') if p['github'] else '')+(link(p['readme'],'View README','button button-secondary') if p['readme'] else '')+(link(p['demo'],'Watch Demo','button button-secondary') if p['demo'] else f'<span class="unavailable">{e(p.get("demoNote",""))}</span>')
 gallery=''.join(f'<figure>{media(p,"../",i)}<figcaption>{e(im["caption"])}</figcaption></figure>' for i,im in enumerate(p['images']))
 diagram='<ol class="system-flow" aria-label="시스템 데이터 흐름">'+''.join(f'<li><span class="flow-number">0{i+1}</span><span>{e(t)}</span></li>' for i,t in enumerate(p['diagram']))+'</ol>'
 nxt=P[(P.index(p)+1)%len(P)]
 return f'''<div class="container project-detail" id="home"><a class="back-link" href="../index.html#projects">← 전체 프로젝트</a><header class="detail-header"><p class="eyebrow">{p['number']} / {e(p['category'])}</p><div class="detail-title"><h1>{e(p['name'])}</h1><span class="status">{e(p['status'])}</span></div><p class="detail-summary">{e(p['summary'])}</p><p class="detail-meta">{e(p['period'])}<span>{e(p['team'])}</span></p>{tags(p)}<div class="detail-actions">{actions}</div></header><div class="detail-gallery">{gallery}</div>
<div class="detail-main"><section><p class="eyebrow">PROJECT OVERVIEW</p><h2>어떤 시스템인가요?</h2><p>{e(p['overview'])}</p><div class="role-callout"><span>MY ROLE</span><strong>{e(p['role'])}</strong></div><h3 class="subheading">MY IMPLEMENTATION</h3><ul class="implementation-list">{''.join(f'<li>{e(x)}</li>' for x in p['implementation'])}</ul></section><section><p class="eyebrow">SYSTEM FLOW</p><h2>데이터가 동작으로 이어지는 구조</h2>{diagram}<h3 class="subheading">TEAM / EXTERNAL</h3><p class="external-copy">{e(p['external'])}</p>{link(p['source'],'구현 코드 확인') if p['source'] else '<p class="external-copy">원본 GX Works·HMI 파일과 발표 자료 보유</p>'}</section></div>
<section class="case-study"><div class="case-title"><p class="eyebrow">ENGINEERING NOTE</p><h2>문제를 마주했을 때</h2></div><div class="case-grid"><div><h3>문제와 판단</h3><p>{e(p['problem'])} {e(p['decision'])}</p></div><div><h3>결과와 남은 한계</h3><p>{e(p['result'])}</p><p class="limitation">{e(p['limitation'])}</p></div></div></section><nav class="project-pagination" aria-label="프로젝트 이동"><a href="../index.html#projects">← 프로젝트 목록</a><a href="{nxt['id']}.html">다음 프로젝트: {e(nxt['name'])} →</a></nav></div>'''
(ROOT/'index.html').write_text(shell('Robot Software / Embedded',homepage()),encoding='utf-8')
(ROOT/'projects').mkdir(exist_ok=True)
for p in P:
 (ROOT/'projects'/f'{p["id"]}.html').write_text(shell(p['name'],detail(p),'../',p['summary']),encoding='utf-8')
print('Generated index.html and 6 project pages.')
